### PR TITLE
Introduce abstraction for CurrencyId into farming pallet

### PR DESCRIPTION
**Pull request by RustNinja**
Farming Pallet is **very useful** and this PR focused to Introduce abstraction for currency id into farming pallet via `loose pallet coupling` that is more flexible and preferable in most cases.

Here is the changes that was added:

- introduce associated type `CurrencyId` for farming pallet
- update all runtimes (`Polkadot`/`Kusama`)
- update unit tests and mock runtimes

Once this changes was merged anyone will able to use farming pallet in their runtimes.

### CODE REVIEW

**Comment by ark930** [comment]
Run command `SKIP_WASM_BUILD= cargo check -p node-cli --locked --features "with-all-runtime"` failed

**Comment by gianfra-t** [comment]
Hi @ark930, we have fixed the failing command and merged with the latest dev branch. Running tests locally seems to work okay, could you please give it a try at the CI?

**Comment by gianfra-t** [comment]
Sorry it failed with check. Must have broken with the merge. 
Could you please tell me what commands does the CI run so I can test all of them locally?

**Comment by ark930** [comment]
@gianfra-t  `make check-all && make clippy && make test-all`

**Comment by gianfra-t** [comment]
Thanks @ark930, I have replaced the currency id in the benchmarks [for the default](https://github.com/bifrost-finance/bifrost/pull/960/commits/618af81c6f05e067fde6abf4656a9568c6ddf699#diff-37e2902485122e7a7f291260b09499aca3eaa04b26f5b28ae5991885c501f9ceR34) so it is compatible with the generic implementation. I believe this should not introduce any fundamental difference, but please let me know.

**Review by ark930 — APPROVED** [review]

**Pull request merged**
